apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-express
  labels:
    app: kubernetes-express
spec:
  replicas: 1
  template:
    metadata:
      name: kubernetes-express
      labels:
        app: kubernetes-express
    spec:
      containers:
        - name: kubernetes-express
          image: "robertoachar/kubernetes-express:1.0.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # resources:
          #   requests:
          #     cpu: 1
          #     memory: 100M
          #   limits:
          #     cpu: 1
          #     memory: 100M
