apiVersion: v1
kind: Service
metadata:
  name: kubernetes-express
  labels:
    app: kubernetes-express
spec:
  selector:
    app: kubernetes-express
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
